config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|fr|CH-fr|th/ do
    resources :accounts do
      resources :transactions
    end
    resources :users

    root 'welcome#index'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :authorize

  def new
    @transaction = Transaction.new
    @account = Account.find(params[:account_id])
    @balance = calculateAccountCurrentBalance(@account.id)
  end

  def create
    @account = Account.find(params[:account_id])
    @transactionSave = @account.transactions.new(transaction_params)
    if @transactionSave.save
      flash[:success] = t('.success-transaction')
      redirect_to account_path(@account)
    else
      flash[:error] = t('.error-transaction')
      render 'new'
    end
  end

  def destroy
    @account = Account.find(params[:account_id])
    @transaction = @account.transactions.find(params[:id])
    if @transaction.destroy
      flash[:success] = t('.success-transaction-destroy')
      redirect_to request.referer
    else
      flash[:error] = t('.error-transaction-destroy')
      redirect_to request.referer
    end
  end

private

  def transaction_params
    params.require(:transaction).permit(:label, :amount, :account_id, :user_id, :withdraw)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/new.html.erb
<h2><%= @account.name %> -
<% if params[:isWithdraw] == "true" %>
  <span class='red-text'><%= t('.withdraw') %></span>
<% else %>
  <span class='green-text'><%= t('.deposit') %></span>
<% end %>
</h2>

<%= simple_form_for([@account, @account.transactions.build]) do |f| %>

  <div class="row">
    <h4 class="center"><em><%= t('.balance') %>: <%= @balance %></em></h4>
  </div>

  <div class="row hide">
    <%= f.input :account_id, :as => :hidden, :input_html => { :value => @account.id } %>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <%= f.input :withdraw, :as => :hidden, :input_html => { :value => params[:isWithdraw] } %>
  </div>

  <div class="row">
    <%= f.input :label, :autofocus => true, wrapper_html: {class: 's12 m6 offset-m3'} %>
    <%= f.input :amount, wrapper_html: {class: 's12 m4 offset-m4'} %>
  </div>

  <div class="row center">
    <%= f.button :submit, value: t('.add'), data: { disable_with: t('.adding')+"..." } %>
    <% if request.referer != nil %>
      <a href="<%= request.referer %>" class="btn grey"><%= t('.cancel') %></a>
    <% else %>
      <a href="<%= accounts_path %>" class="btn grey"><%= t('.cancel') %></a>
    <% end %>
  </div>

<% end %>