config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|fr|CH-fr|th/ do
    resources :accounts do
      resources :transactions
    end
    resources :users

    root 'welcome#index'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <div class="card-panel hoverable center alert alert-<%= key %>">
        <span>
          <%= value %><i class="material-icons right">close</i>
        </span>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
      <%= t('.copyright') %>
      <a class="grey-text text-lighten-4 right" href="<%= root_path %>"><%= t('.link-homepage') %></a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <a href="<%= root_path %>" class="brand-logo">MoneyManager</a>
      <a data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <%= menus.html_safe %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <%= menus.html_safe %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main>
      <div class="container">
        <%= render 'layouts/flashes' %>
        <div class="row">
          <% if current_user %>
            <p><%= t('.signed_in_as') %> <%= current_user.username %></p>
          <% else %>
            <p><%= link_to t(".login"), login_path %> | <%= link_to t(".signup"), signup_path %></p>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>