config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|fr|CH-fr|th/ do
    resources :accounts do
      resources :transactions
    end
    resources :users

    root 'welcome#index'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    get '/logout' => 'sessions#destroy'

    get '/signup' => 'users#new'
    post '/users' => 'users#create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, :uniqueness => {:scope => [:name, :user_id]}
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authorize

  def index
    @addTooltip = t('.tooltip-add')
    @removeTooltip = t('.tooltip-remove')
    @editTooltip = t('.tooltip-edit')

    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    if @account.save
      flash[:success] = t('.success')
      redirect_to accounts_path
    else
      flash[:error] = t('.error')
      render 'new'
    end
  end

  def show
    @account = Account.find(params[:id])
    @balance = calculateAccountCurrentBalance(@account.id)
  end

  def edit
    @account = Account.find(params[:id])
    @nameLabel = t('.nameAccount')
    @confirmText = t('.sure')
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      flash[:success] = t('.success-account-update')
      redirect_to accounts_path
    else
      @account.name = Account.find(params[:id]).name #Put back the name of the account before trying the update
      flash[:error] = t('.error-account-update')
      render 'edit'
    end
  end

  def destroy
    @account = Account.find(params[:id])
    if @account.destroy
      flash[:success] = t('.success-account-destroy')
      redirect_to accounts_path
    else
      flash[:error] = t('.error-account-destroy')
      render 'edit'
    end
  end

  def printAccountLatestTransactions(account_id)
    html = ""
    transactions = Transaction.all.where(account_id: account_id).where(user_id: current_user.id).order(created_at: :DESC).limit(10)
    transactions.each do |transaction|
      if transaction.withdraw
        html += '<li class="collection-item red row white-text"><span class="col s1 center">-</span><span class="col s5 truncate">'+ transaction.label + '</span>'
        html += '<span class="col s3">' + number_to_currency(transaction.amount).to_s + '</span>'
        html += '<span class="col s2">' + l(transaction.created_at, format: :date_day_month) + '</span>'
        html += view_context.link_to '<i class="material-icons white-text">delete</i>'.html_safe, [transaction.account, transaction], method: :delete, data: { confirm: t('accounts.destroy.transactions.confirmation') }, class: "transaction-row"
        html += '</li>'
      else
        html += '<li class="collection-item green row white-text"><span class="col s1 center">+</span><span class="col s5 truncate">' + transaction.label + '</span>'
        html += '<span class="col s3">' + number_to_currency(transaction.amount).to_s + '</span>'
        html += '<span class="col s2">' + l(transaction.created_at, format: :date_day_month) + '</span>'
        html += view_context.link_to '<i class="material-icons white-text normal">delete</i>'.html_safe, [transaction.account, transaction], method: :delete, data: { confirm: t('accounts.destroy.transactions.confirmation') }, class: "transaction-row"
        html += '</li>'
      end
    end
    if html == ""
      html = '<li class="collection-item center grey lighten-3">' + t('transactions.empty') + '</li>'
      html += '<li class="collection-item center grey lighten-3"><a href="' + new_account_transaction_path(account_id) + '?isWithdraw=true">' + t('transactions.add') + '</a></li>'
    else
      html = '<li class="collection-item grey lighten-2 row"><span class="col s1">+/-</span><span class="col s5 truncate">' + t('transactions.label') + '</span><span class="col s3">' + t('transactions.amount') + '</span><span class="col s2">' + t('transactions.date') + '</span></li>' + html
    end
    html
  end
  helper_method :printAccountLatestTransactions

  def account_params
    params.require(:account).permit(:name)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<h2><strong><%= t('.title-part-one') %>: </strong><%= @account.name %></h2>

<%= simple_form_for @account do |f| %>

  <div class="row">
    <%= f.input :name, :autofocus => true, wrapper_html: {class: 's12 m6 offset-m3 l4 offset-l4'} %>
  </div>

  <div class="row center">
    <%= f.button :submit, value: t('.update'), data: { disable_with: t('.updating')+"..." } %>
    <%= link_to t('.delete').html_safe + ' <i class="material-icons right white-text">delete</i>'.html_safe, account_path(@account), method: :delete, data: { confirm: @confirmText }, class: "btn" %>
  </div>

<% end %>

app/views/accounts/index.html.erb
<h2><%= t('.title') %></h2>

<div class="row">
  <!-- Card to add a new account -->
  <div class="col s12 m6 l4">
    <div class="card hoverable grey lighten-3 black-text">
      <div class="card-content">
        <span class="card-title"><%= t('.new-account') %></span>
        <p><strong><%= t('.balance') %> : </strong><%= number_to_currency(0) %></p>
      </div>
      <div class="card-action center">
        <%= link_to t('.add-account'), new_account_path, class: "waves-effect btn" %>
      </div>
    </div>
  </div>
  <!-- Display all the accounts created -->
  <% @accounts.each do |account| %>
  <div class="col s12 m6 l4">
    <div class="card hoverable">
      <div class="card-content">
        <span class="card-title"><%= account.name %></span>
        <a href="<%= edit_account_url(account) %>" class="waves-effect waves-light btn-flat right account-edit tooltipped black-text" data-tooltip="<%= @editTooltip %>"><i class="material-icons">edit</i></a>
        <p><strong><%= t('.balance') %> : </strong> <%= calculateAccountCurrentBalance(account.id) %></p>
      </div>
      <div class="card-action">
        <a href="<%= new_account_transaction_path(account) %>?isWithdraw=false" class="waves-effect waves-light btn account-add tooltipped light-green" data-tooltip="<%= @addTooltip %>" ><i class="material-icons">add</i></a>
        <a href="<%= new_account_transaction_path(account) %>?isWithdraw=true" class="waves-effect waves-light btn account-remove tooltipped" data-tooltip="<%= @removeTooltip %>"><i class="material-icons">remove</i></a>
        <a href="<%= account_url(account) %>" class="waves-effect btn-flat black-text right" style="margin-right: 0;"><%= t('.show') %></a>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/accounts/new.html.erb
<h2><%= t('.title') %></h2>

<%= simple_form_for @account do |f| %>

  <div class="row">
    <%= f.input :name, :autofocus => true, wrapper_html: {class: 's12 m6 offset-m3'} %>
  </div>

  <div class="row center">
    <%= f.button :submit, value: t('.create'), data: { disable_with: t('.creating')+"..." } %>
  </div>

<% end %>

app/views/accounts/show.html.erb
<h2><strong><%= t('.title-part-one') %></strong>: <%= @account.name %></h2>
<div class="row">
  <div class="col s12 m6">
    <div class="card-panel grey lighten-2">
      <p class="balance center"><%= t('.balance') %><br><span class="<%= if @balance.to_f <= 1000 then "red-text" else "green-text" end %>"><%= @balance %></span></p>
    </div>
  </div>
  <div class="col s12 m6">
    <ul class="collection with-header">
      <li class="collection-header"><h4><%= t('.latest-transactions') %></h4></li>
      <%= printAccountLatestTransactions(@account.id).html_safe %>
    </ul>
  </div>
</div>